In [1]:
%load_ext autoreload
%autoreload 2
%load_ext snakeviz

In [2]:
import numpy as np
import cupy as cp

from LegendreDecomposition import LD_cupy

In [3]:
N = 20
X = np.random.uniform(0, 0.1, size=(N, N, N, N))
X

array([[[[9.24368402e-02, 7.49936776e-02, 2.92133299e-02, ...,
          5.37871839e-02, 6.40488503e-02, 1.63894314e-02],
         [8.17596505e-02, 2.22316802e-02, 2.09232289e-02, ...,
          1.72771282e-02, 1.14049843e-02, 8.25088026e-02],
         [7.01404875e-02, 7.06716987e-02, 2.09161972e-02, ...,
          1.26294820e-02, 7.50096106e-02, 4.06506657e-02],
         ...,
         [4.71818565e-03, 9.34357314e-02, 2.26918644e-02, ...,
          9.43817105e-02, 4.53009954e-02, 6.21949722e-02],
         [5.35670902e-02, 9.57611729e-02, 3.82765555e-02, ...,
          7.99080643e-02, 3.50430786e-02, 3.81847730e-02],
         [1.91367394e-02, 8.36942634e-02, 7.01800453e-02, ...,
          4.42876805e-02, 3.20455183e-02, 3.60204303e-02]],

        [[7.15686070e-02, 5.31337589e-02, 2.65644025e-02, ...,
          1.23582854e-02, 8.56141391e-02, 3.86084209e-02],
         [4.12602445e-02, 1.71756219e-02, 4.11965457e-04, ...,
          7.28120651e-02, 4.76902445e-02, 6.19545590e-02],
        

In [4]:
%%snakeviz -t
# %snakeviz -t
LD_cupy(X, order=2, gpu=False, verbose=False)

 
*** Profile stats marshalled to file '/tmp/tmp8ekdiip7'.
Opening SnakeViz in a new tab...
snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2Ftmp%2Ftmp8ekdiip7


In [ ]:
N = 25
X = np.random.uniform(0, 0.1, size=(N, N, N, N))
X

array([[[[2.24951934e-03, 8.65972081e-02, 1.18759624e-02, ...,
          7.18036150e-02, 7.14949036e-02, 5.50570028e-02],
         [3.96563230e-03, 2.19832194e-02, 9.58980570e-02, ...,
          1.73721909e-02, 6.55732466e-02, 9.73842517e-02],
         [9.03529307e-02, 3.63969810e-02, 2.18380051e-02, ...,
          8.25763684e-02, 1.11842919e-02, 8.63545027e-02],
         ...,
         [8.48235289e-02, 9.92407686e-02, 5.51749966e-02, ...,
          6.17817383e-02, 8.95528050e-02, 4.35275011e-03],
         [5.18728504e-02, 3.13098723e-03, 8.67718245e-02, ...,
          1.32937219e-02, 1.51513388e-03, 5.38177837e-02],
         [9.34833358e-02, 5.38358476e-02, 6.27059797e-02, ...,
          3.88596876e-02, 5.54038525e-02, 8.29613953e-02]],

        [[6.69625055e-02, 9.75043308e-02, 9.11867483e-02, ...,
          9.33646370e-02, 4.99300310e-02, 5.53820138e-02],
         [2.86042192e-02, 1.42386121e-02, 6.08403128e-02, ...,
          4.23239285e-02, 9.55614084e-02, 2.41149998e-02],
        

In [ ]:
%%snakeviz -t
# %snakeviz -t
LD_cupy(X, order=2, gpu=False, verbose=False)

 
*** Profile stats marshalled to file '/tmp/tmp14jy2zpa'.
Opening SnakeViz in a new tab...
snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2Ftmp%2Ftmp14jy2zpa


In [ ]:
N = 30
X = np.random.uniform(0, 0.1, size=(N, N, N, N))
X

array([[[[0.07709508, 0.09061826, 0.06077274, ..., 0.06591587,
          0.03812673, 0.02824721],
         [0.07897541, 0.08867419, 0.05549777, ..., 0.0867922 ,
          0.03789303, 0.05088472],
         [0.05313961, 0.03154675, 0.05564384, ..., 0.09068686,
          0.0125667 , 0.08263225],
         ...,
         [0.0433561 , 0.09540934, 0.01773749, ..., 0.06877641,
          0.06623261, 0.00780357],
         [0.04880565, 0.02219704, 0.06888974, ..., 0.01372094,
          0.04532542, 0.01869948],
         [0.00600636, 0.08369066, 0.01415015, ..., 0.06062227,
          0.06356307, 0.0535159 ]],

        [[0.09078751, 0.0917224 , 0.03413378, ..., 0.09340308,
          0.0009709 , 0.05795389],
         [0.01704227, 0.03595477, 0.07471163, ..., 0.07216807,
          0.06226423, 0.02721163],
         [0.09392823, 0.01942294, 0.06220947, ..., 0.06117937,
          0.06263   , 0.08731872],
         ...,
         [0.09953981, 0.09043942, 0.00846304, ..., 0.02618603,
          0.0474644 , 0.0

In [ ]:
%%snakeviz -t
# %snakeviz -t
LD_cupy(X, order=2, gpu=False, verbose=False)

 
*** Profile stats marshalled to file '/tmp/tmp2k7rxv1d'.
Opening SnakeViz in a new tab...
snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2Ftmp%2Ftmp2k7rxv1d


In [ ]:
N = 32
X = np.random.uniform(0, 0.1, size=(N, N, N, N))
X

array([[[[9.21111003e-02, 4.57734448e-02, 1.17039628e-02, ...,
          7.42056583e-02, 8.96100435e-02, 4.53780861e-02],
         [1.52337659e-02, 9.78417761e-02, 3.85874122e-02, ...,
          8.59690405e-02, 3.13334596e-02, 9.76550700e-02],
         [5.44351989e-02, 1.92523732e-02, 6.98230766e-02, ...,
          5.96651112e-02, 3.94628512e-02, 9.41546203e-03],
         ...,
         [5.05740343e-02, 2.40878824e-02, 2.24331849e-02, ...,
          1.72281804e-02, 4.03221461e-02, 4.91194865e-02],
         [1.05792016e-02, 3.99031950e-02, 3.17603331e-02, ...,
          2.42209545e-02, 2.59068739e-02, 1.50002684e-02],
         [7.54288768e-02, 9.44863837e-02, 6.64520922e-02, ...,
          5.21896468e-02, 4.19542098e-02, 5.37129083e-02]],

        [[6.24447618e-02, 4.65650970e-02, 7.58591273e-02, ...,
          9.09942260e-02, 6.00335319e-02, 2.70010150e-02],
         [6.50001788e-02, 6.91534398e-03, 6.30751753e-02, ...,
          3.60958732e-02, 7.87724308e-02, 6.89392794e-02],
        

In [ ]:
%%snakeviz -t
# %snakeviz -t
LD_cupy(X, order=2, gpu=False, verbose=False)

 
*** Profile stats marshalled to file '/tmp/tmpi048xpxm'.
Opening SnakeViz in a new tab...
snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2Ftmp%2Ftmpi048xpxm
